name: CI

on:
  push:
    branches: [ "main", "ci-test"]
  pull_request:
    branches: [ "main" ]

jobs:
  guix-build:

    runs-on: ubuntu-latest

    steps:

    - name: Guix cache
      uses: actions/cache@v3
      with:
        path: .cache/guix
        key:  ${{runner.OS}}-guix
        restore-keys:  ${{runner.OS}}-guix
    - name: Install Guix
      id: install-guix
      uses: PromyLOPh/guix-install-action@v1
      with:
        channels: |-
          (list
           (channel
            (inherit %default-guix-channel)
            (url "https://codeberg.org/guix/guix-mirror")))
 
    - uses: actions/checkout@v3
    - name: build
      run: guix build -f guix.scm